package it.uniroma3.siwEsameUltimate.model;

import java.util.Date;
import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Autore {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long Id;
	private String nome,cognome;
	private String nazionalita;
	private Date dataNascita,dataMorte;
	@OneToMany
	private Map<Long , Opera> opereRealizzate;	//long refer to the AutoGeneratedValue
	
	
	
	public String getCognome() {
		return cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getNazionalita() {
		return nazionalita;
	}

	public void setNazionalita(String nazionalita) {
		this.nazionalita = nazionalita;
	}

	public void addOpera(Opera opera){
		this.opereRealizzate.put(opera.getId(), opera);
	}
	
	public Long getId() {
		return Id;
	}
	
	public void setId(Long id) {
		Id = id;
	}
	
	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	public Date getDataNascita() {
		return dataNascita;
	}
	
	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}
	
	public Date getDataMorte() {
		return dataMorte;
	}
	
	public void setDataMorte(Date dataMorte) {
		this.dataMorte = dataMorte;
	}
	
	public Map<Long, Opera> getOpereRealizzate() {
		return opereRealizzate;
	}
	
	public void setOpereRealizzate(Map<Long, Opera> opereRealizzate) {
		this.opereRealizzate = opereRealizzate;
	}
}